apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c", "while true; do curl -s http://nginx-service; sleep 0.5; done"]