apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo
  labels:
    release: kube-prometheus-stack

spec:
  selector:
    matchLabels:
      app: demo

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
