name: Dockerfile Security Scan

on:
  push:
    branches: [ "feat/scanner_docker" ]

jobs:
  build:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # Tell Trivy to scan the current directory for config/dockerfile issues
          scan-type: 'config'
          hide-progress: false
          # This makes the pipeline fail if it finds issues
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
