apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    app: demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}