apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.1.100:3260
    targetPortalWebIQN: iqn.2016-08.com.example.storage.target
    lun: 0
    secretRef:
      name: iscsi-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: iscsi-secret
type: kubernetes.io/iscsi
data:
  chapUsername: <base64 encoded chap username>
  chapPassword: <base64 encoded chap password>
---
apiVersion: v1
kind: Pod
metadata:
  name: iscsi-pod
spec:
  containers:
  - name: iscsi-container
    image: nginx:latest
    volumeMounts:
    - name: iscsi-pv
      mountPath: /data
  volumes:
  - name: iscsi-pv
    persistentVolumeClaim:
      claimName: iscsi-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
