name: Manual Trigger Workflow with loglevel & tags
on:
  push:
    branches:
      - notsubcribers
jobs:
  sns-review:
    runs-on: ubuntu-latest
    steps:
      - name: Starting the scanning
        run: echo "Start the scanning"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install boto3 && python main.py