name: Ping Action

on: [push]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ping script
        run: bash scripts/bash/net-troubleshoting/main.sh 8.8.8.8