name: Manual Trigger Workflow with loglevel & tags
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the purpose of run
        run: echo  ${{ inputs.tags }} purpose